site_name: Rarita National Football Team Construction and Implementation
theme:
  name: material
  palette:
    scheme: deep purple
  features:
    - navigation.tabs
    - content.code.annotate
repo_url: https://github.com/ACTL4001-T1-2022/github-showcase-page-group-acc

nav:
    - Home: index.md
    - Team Selection: team_selection.md
    - Economic: 
        - 'economic/overview.md'
        - 'economic/rev_exp.md'
        - 'economic/indices.md'
        - 'economic/industries.md'
        - 'economic/stress_test.md'
        - 'economic/assumptions.md'
    - Implementation Plan: implementation.md
    - Risk Analysis: risk.md
    
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences  
  - pymdownx.arithmatex:
      generic: true
  - codehilite
  - pymdownx.details
  - admonition
  - attr_list
  - md_in_html
      
# for pymdown.arithmatex 
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

